# Generated by Django 3.2.16 on 2026-04-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='full_adress',
            new_name='full_address',
        ),
    ]
